In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('primary-results.csv' )

In [30]:
df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078

In [31]:
len(df)

24611

In [32]:
df.groupby('candidate')

In [33]:
#sobre a coluna votos fazer as operações min media e max
df.groupby('candidate').aggregate({'votes': [min,np.mean,max]})

                votes
                  min         mean     max
candidate
 No Preference      0    23.225071     580
 Uncommitted        0     0.434343      16
Ben Carson          0   338.258238    9945
Bernie Sanders      0  2844.019501  434656
Carly Fiorina       0   139.366972    3612
Chris Christie      1   223.422018    7144
Donald Trump        0  3709.576408  179130
Hillary Clinton     0  3731.855410  590502
Jeb Bush            2   609.103226    9575
John Kasich         0  1160.052705  101217
Marco Rubio         0  1299.834051  111898
Martin O'Malley     0     7.595960     152
Mike Huckabee       2    33.787879     565
Rand Paul           2    85.646465    1633
Rick Santorum       0    18.000000     234
Ted Cruz            0  2120.191299  147721

In [34]:
df.groupby('county').aggregate({'votes': [min,np.mean,max]})

               votes
                 min          mean     max
county
Abbeville        157    685.000000    1501
Abbot              0      0.500000       1
Abington          30    570.000000    1352
Acadia           129   1104.833333    1862
Accomack         210    964.285714    2068
Acton              2    770.400000    2884
Acushnet          14    332.125000     783
Ada             1663   9621.000000   20156
Adair              0    369.705882    1512
Adams              0   1124.513514    9754
Addison            1     57.333333     251
Agawam            54    879.625000    1943
Aiken           1207   4793.625000    9027
Alachua         1902   9776.333333   17733
Alamance        1300   4947.166667    7374
Alameda         3208  45338.600000  107102
Alamosa           90    128.500000     167
Albany             4   3743.857143   20422
Albany-Natrona     0     19.000000      39
Albemarle        665   4258.857143    8284
Albion             1      1.500000       2
Alburgh            5     78.000000     315
Alcona           138    494.500000    1111
Alcorn           302   1125.000000    2901
Alexander          0    718.214286    2830
Alexandria       272   5233.285714   16281
Alfalfa           18    200.000000     421
Alford             0     22.500000      84
Alfred             3      4.000000       5
Alger             99    370.166667     622
...              ...           ...     ...
Woonsocket       143    866.400000    1674
Worcester          1   2274.500000   12132
Worth              0    199.321429    1890
Worthington        0     59.375000     251
Wrentham          10    427.000000     901
Wright             0    277.476190    1874
Wyandot          108    968.833333    1896
Wyoming           31   1134.600000    3547
Wythe            148    630.285714    1873
Yadkin           282   1526.000000    3436
Yakima           123   3563.400000   14872
Yalobusha         70    542.666667    1214
Yamhill         1879   4598.800000    6843
Yancey           165    882.000000    1386
Yankton          184    460.400000     706
Yarmouth          15    799.700000    2245
Yates            369    737.000000    1296
Yavapai         3259   9264.000000   17005
Yazoo            152    852.666667    2203
Yell              47    504.142857     911
Yellowstone     1934   7449.600000   17925
Yoakum             9    210.571429     685
Yolo             557   6171.000000   12567
York              17   6526.111111   41948
Young            120    624.857143    1945
Yuba             198   1405.600000    3210
Yuma              33   2008.571429    4390
Zapata             0    390.714286    1969
Zavala             0    275.714286    1557
Ziebach           11     67.800000     132

[2633 rows x 3 columns]

In [37]:
df[df['votes']== 590502]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.57

In [38]:
df.groupby('candidate').aggregate({'fraction_votes': [min,np.mean,max]})

                fraction_votes
                           min      mean       max
candidate
 No Preference           0.000  0.006484  0.030000
 Uncommitted             0.000  0.000455  0.013000
Ben Carson               0.000  0.058941  0.415000
Bernie Sanders           0.000  0.493316  1.000000
Carly Fiorina            0.000  0.022097  0.117000
Chris Christie           0.002  0.017773  0.087195
Donald Trump             0.000  0.466217  0.915000
Hillary Clinton          0.000  0.461302  1.000000
Jeb Bush                 0.004  0.044524  0.121000
John Kasich              0.000  0.122869  0.639000
Marco Rubio              0.000  0.146959  0.627000
Martin O'Malley          0.000  0.008303  0.132000
Mike Huckabee            0.003  0.024192  0.096000
Rand Paul                0.006  0.034061  0.096000
Rick Santorum            0.000  0.009960  0.073000
Ted Cruz                 0.000  0.243453  1.000000

In [41]:
df[(df['fraction_votes'] ==1) & (df['candidate']== 'Hillary Clinton')]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
8142,Maine,ME,Amity,92300012.0,Democrat,Hillary Clinton,1,1.0
8160,Maine,ME,Atkinson,92300020.0,Democrat,Hillary Clinton,1,1.0
8168,Maine,ME,Avon,92300024.0,Democrat,Hillary Clinton,1,1.0
8186,Maine,ME,Beaver Cove,92300033.0,Democrat,Hillary Clinton,1,1.0
8188,Maine,ME,Beddington,92300034.0,Democrat,Hillary Clinton,1,1.0
8292,Maine,ME,Caswell,92300088.0,Democrat,Hillary Clinton,1,1.0
8334,Maine,ME,Crawford,92300111.0,Democrat,Hillary Clinton,1,1.0
8400,Maine,ME,Edinburg,92300144.0,Democrat,Hillary Clinton,1,1.0
8576,Maine,ME,Lakeville,92300235.0,Democrat,Hillary Clinton,1,1.0
8650,Maine,ME,Masardis,92300274.0,Democrat,Hillary Clinton,1,1.0
8700,Maine,ME,Moscow,92300301.0,Democrat,Hillary Clinton,1,1.0
8710,Maine,ME,New Canada,92300308.0,Democrat,Hillary Clinton,1,1.0
8744,Maine,ME,Northfield,92300322.0,Democrat,Hillary Clinton,1,1.0
8770,Maine,ME,Otis,92300338.0,Democrat,Hillary Clinton,1,1.0
8828,Maine,ME,Portage Lake,92300364.0,Democrat,Hillary Clinton,1,1.0
8866,Maine,ME,Roque Bluffs,92300384.0,Democrat,Hillary Clinton,1,1.0
8932,Maine,ME,Springfield,92300421.0,Democrat,Hillary Clinton,1,1.0
8974,Maine,ME,Sweden,92300438.0,Democrat,Hillary Clinton,1,1.0
9018,Maine,ME,Wade,92300464.0,Democrat,Hillary Clinton,1,1.0
9052,Maine,ME,Wellington,92300480.0,Democrat,Hillary Clinton,1,1.0
9070,Maine,ME,Westmanland,92300488.0,Democrat,Hillary Clinton,1,1.0
14088,Nebraska,NE,Hayes,31085.0,Democrat,Hillary Clinton,9,1.0
14174,Nebraska,NE,Thomas,31171.0,Democrat,Hillary Clinton,1,1.0

In [10]:
def a(x):
    return x['votes'].sum() >30000
df.groupby('state').filter(a)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
5,Alabama,AL,Barbour,1005.0,Democrat,Hillary Clinton,2567,0.906
6,Alabama,AL,Bibb,1007.0,Democrat,Bernie Sanders,246,0.197
7,Alabama,AL,Bibb,1007.0,Democrat,Hillary Clinton,942,0.755
8,Alabama,AL,Blount,1009.0,Democrat,Bernie Sanders,395,0.386
9,Alabama,AL,Blount,1009.0,Democrat,Hillary Clinton,564,0.551
10,Alabama,AL,Bullock,1011.0,Democrat,Bernie Sanders,178,0.066
11,Alabama,AL,Bullock,1011.0,Democrat,Hillary Clinton,2451,0.913
12,Alabama,AL,Butler,1013.0,Democrat,Bernie Sanders,156,0.065
13,Alabama,AL,Butler,1013.0,Democrat,Hillary Clinton,2196,0.921
14,Alabama,AL,Calhoun,1015.0,Democrat,Bernie Sanders,1425,0.218
15,Alabama,AL,Calhoun,1015.0,Democrat,Hillary Clinton,5011,0.765
16,Alabama,AL,Chambers,1017.0,Democrat,Bernie Sanders,312,0.095
17,Alabama,AL,Chambers,1017.0,Democrat,Hillary Clinton,2899,0.886
18,Alabama,AL,Cherokee,1019.0,Democrat,Bernie Sanders,268,0.249
19,Alabama,AL,Cherokee,1019.0,Democrat,Hillary Clinton,712,0.661
20,Alabama,AL,Chilton,1021.0,Democrat,Bernie Sanders,289,0.246
21,Alabama,AL,Chilton,1021.0,Democrat,Hillary Clinton,860,0.731
22,Alabama,AL,Choctaw,1023.0,Democrat,Bernie Sanders,273,0.124
23,Alabama,AL,Choctaw,1023.0,Democrat,Hillary Clinton,1772,0.802
24,Alabama,AL,Clarke,1025.0,Democrat,Bernie Sanders,213,0.063
25,Alabama,AL,Clarke,1025.0,Democrat,Hillary Clinton,3148,0.930
26,Alabama,AL,Clay,1027.0,Democrat,Bernie Sanders,135,0.137
27,Alabama,AL,Clay,1027.0,Democrat,Hillary Clinton,807,0.818
28,Alabama,AL,Cleburne,1029.0,Democrat,Bernie Sanders,72,0.238
29,Alabama,AL,Cleburne,1029.0,Democrat,Hillary Clinton,221,0.732
...,...,...,...,...,...,...,...,...
24487,Wisconsin,WI,Vernon,55123.0,Republican,Donald Trump,2437,0.476
24488,Wisconsin,WI,Vernon,55123.0,Republican,John Kasich,635,0.124
24489,Wisconsin,WI,Vernon,55123.0,Republican,Ted Cruz,1878,0.367
24490,Wisconsin,WI,Vilas,55125.0,Republican,Donald Trump,3241,0.521
24491,Wisconsin,WI,Vilas,55125.0,Republican,John Kasich,832,0.134
24492,Wisconsin,WI,Vilas,55125.0,Republican,Ted Cruz,2006,0.322
24493,Wisconsin,WI,Walworth,55127.0,Republican,Donald Trump,7534,0.341
24494,Wisconsin,WI,Walworth,55127.0,Republican,John Kasich,3328,0.151
24495,Wisconsin,WI,Walworth,55127.0,Republican,Ted Cruz,10719,0.485
24496,Wisconsin,WI,Washburn,55129.0,Republican,Donald Trump,1926,0.497
24497,Wisconsin,WI,Washburn,55129.0,Republican,John Kasich,443,0.114
24498,Wisconsin,WI,Washburn,55129.0,Republican,Ted Cruz,1359,0.351
24499,Wisconsin,WI,Washington,55131.0,Republican,Donald Trump,9580,0.235
24500,Wisconsin,WI,Washington,55131.0,Republican,John Kasich,4823,0.118
24501,Wisconsin,WI,Washington,55131.0,Republican,Ted Cruz,25505,0.626
24502,Wisconsin,WI,Waukesha,55133.0,Republican,Donald Trump,27186,0.221
24503,Wisconsin,WI,Waukesha,55133.0,Republican,John Kasich,18521,0.150
24504,Wisconsin,WI,Waukesha,55133.0,Republican,Ted Cruz,75123,0.610
24505,Wisconsin,WI,Waupaca,55135.0,Republican,Donald Trump,4737,0.429
24506,Wisconsin,WI,Waupaca,55135.0,Republican,John Kasich,817,0.074
24507,Wisconsin,WI,Waupaca,55135.0,Republican,Ted Cruz,5194,0.471
24508,Wisconsin,WI,Waushara,55137.0,Republican,Donald Trump,2391,0.451
24509,Wisconsin,WI,Waushara,55137.0,Republican,John Kasich,371,0.070
24510,Wisconsin,WI,Waushara,55137.0,Republican,Ted Cruz,2390,0.451
24511,Wisconsin,WI,Winnebago,55139.0,Republican,Donald Trump,13293,0.388
24512,Wisconsin,WI,Winnebago,55139.0,Republican,John Kasich,3952,0.115
24513,Wisconsin,WI,Winnebago,55139.0,Republican,Ted Cruz,16049,0.469
24514,Wisconsin,WI,Wood,55141.0,Republican,Donald Trump,6941,0.432
24515,Wisconsin,WI,Wood,55141.0,Republican,John Kasich,1479,0.092
24516,Wisconsin,WI,Wood,55141.0,Republican,Ted Cruz,7220,0.450

In [7]:
df[df['state_abbreviation'] =='AL']['votes'].sum()

1223959

In [15]:
df.groupby(['state_abbreviation', 'candidate'])['votes'].sum()

state_abbreviation  candidate
AK                  Ben Carson            2401
                    Bernie Sanders         440
                    Donald Trump          7346
                    Hillary Clinton         99
                    John Kasich            892
                    Marco Rubio           3318
                    Ted Cruz              7973
AL                  Ben Carson           87517
                    Bernie Sanders       76399
                    Donald Trump        371735
                    Hillary Clinton     309928
                    John Kasich          37970
                    Marco Rubio         159802
                    Ted Cruz            180608
AR                  Ben Carson           23173
                    Bernie Sanders       64868
                    Donald Trump        133144
                    Hillary Clinton     144580
                    John Kasich          15098
                    Marco Rubio         101235
                    Ted Cruz            123873
AZ                  Bernie Sanders      163400
                    Donald Trump        249916
                    Hillary Clinton     235697
                    John Kasich          53040
                    Ted Cruz            132147
CA                  Bernie Sanders     1502043
                    Donald Trump       1174829
                    Hillary Clinton    1940580
                    John Kasich         176620
                                        ...
VA                  Marco Rubio         327042
                    Ted Cruz            173193
VT                  Ben Carson            2544
                    Bernie Sanders      115863
                    Donald Trump         19968
                    Hillary Clinton      18335
                    John Kasich          18543
                    Marco Rubio          11778
                    Ted Cruz              5929
WA                  Bernie Sanders       19159
                    Donald Trump        403003
                    Hillary Clinton       7140
                    John Kasich          52129
                    Ted Cruz             55719
WI                  Bernie Sanders      567936
                    Donald Trump        386370
                    Hillary Clinton     432767
                    John Kasich         155200
                    Ted Cruz            531129
WV                  Bernie Sanders      123860
                    Donald Trump        156245
                    Hillary Clinton      86354
                    John Kasich          13685
                    Ted Cruz             18208
WY                  Bernie Sanders         156
                    Donald Trump            70
                    Hillary Clinton        124
                    John Kasich              0
                    Marco Rubio            189
                    Ted Cruz               644
Name: votes, Length: 290, dtype: int64